theme: jekyll-theme-cayman
title: Color Picker & Palette
logo: Resources/jColorPickerLogo.ico
show_downloads: true
github:
  zip_url: https://github.com/x5qubits/jColorPicker/files/4009889/Release.zip
  tar_url: https://github.com/x5qubits/jColorPicker/files/4009889/Release.zip
